CREATE TABLE "waitlist_entries" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"first_name" text NOT NULL,
	"email" text NOT NULL,
	"whatsapp_number" text,
	"whatsapp_marketing_consent" boolean DEFAULT false NOT NULL,
	"profession" text NOT NULL,
	"city" text,
	"company_name" text,
	"preferred_card_color" text,
	"preferred_card_finish" text,
	"primary_use_cases" jsonb,
	"priority_benefits" jsonb,
	"purchase_intent" text,
	"price_value_perception" text,
	"feedback" text,
	"research_call_opt_in" boolean DEFAULT false NOT NULL,
	"preferred_contact_method" text,
	"founding_price" text DEFAULT '299' NOT NULL,
	"standard_price" text DEFAULT '499' NOT NULL,
	"discount_percent" text DEFAULT '40' NOT NULL,
	"waitlist_status" text DEFAULT 'joined' NOT NULL,
	"referral_code" text NOT NULL,
	"referred_by_code" text,
	"source" text,
	"utm_source" text,
	"utm_medium" text,
	"utm_campaign" text,
	"email_marketing_consent" boolean DEFAULT true NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "waitlist_entries_email_unique" UNIQUE("email"),
	CONSTRAINT "waitlist_entries_referral_code_unique" UNIQUE("referral_code")
);
